openapi: 3.0.1
info:
  title: Test-Cache
  description: ''
  version: '1.0'
servers:
  - url: https://apim-poc-dev-public.azure-api.net/test-cache
paths:
  /json:
    get:
      summary: test
      description: test
      operationId: test
      responses:
        '200':
          description: ''
  /*:
    get:
      summary: test-cache_GET
      operationId: 6852b50f0f81fc4fb470819f
      responses:
        '200':
          description: ''
    post:
      summary: test-cache_POST
      operationId: 6852b50fbfafb1db3cba384a
      responses:
        '200':
          description: ''
    put:
      summary: test-cache_PUT
      operationId: 6852b50f6f433c2a438cbf05
      responses:
        '200':
          description: ''
    delete:
      summary: test-cache_DELETE
      operationId: 6852b50f7071fdd251436e0c
      responses:
        '200':
          description: ''
    head:
      summary: test-cache_HEAD
      operationId: 6852b50ff7accf66d8393b08
      responses:
        '200':
          description: ''
    options:
      summary: test-cache_OPTIONS
      operationId: 6852b50faadf8b3b6230962d
      responses:
        '200':
          description: ''
    patch:
      summary: test-cache_PATCH
      operationId: 6852b50f35c2791aacf15dea
      responses:
        '200':
          description: ''
    trace:
      summary: test-cache_TRACE
      operationId: 6852b50f7053a683224dfccf
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]