openapi: 3.0.1
info:
  title: Test-Cache-2
  description: ''
  version: '1.0'
servers:
  - url: https://apim-poc-dev-public.azure-api.net/test-cache-2
paths:
  /json:
    get:
      summary: test
      operationId: test
      responses:
        '200':
          description: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]